
#events
#{

#}
#http
#{
 server {
        # configuration of HTTP virtual server 1
        listen 80;
        location /one {
            # configuration for processing URIs starting with '/one'
            allow_pass asas;
            We are in location block 2;
           This needs another type of parsing;
        }
       location /two {
            # configuration for processing URIs starting with '/two'
            hi;
           We are inside location block 2;
       } 
        root 
        
                    /root ;
        
        
        return;
    }

#}

#nginx -t -c $(pwd)/nginx.conf 